FIX: Prevent negative column width, row height
ironcalc/IronCalc pull request #167
Opened 2024-12-07 21:27 UTC by enjoythecode

fixes !165

2024-12-07 21:27 UTC, enjoythecode commented
fixes ironcalc/ironcalc!165

2024-12-07 21:27 UTC, enjoythecode commented
hmm, I can't reference that issue apparently.

2024-12-07 21:28 UTC, enjoythecode commented
fixes #165

there we go.

2024-12-07 21:36 UTC, enjoythecode commented
@nhatcher  do you have a preferred way of reaching out to you when a PR is ready for review?

this is ready for your review, thanks for your guidance.

2024-12-08 01:17 UTC, nhatcher requested changes
Excellent job.

I let a couple of minor comments

2024-12-08 01:17 UTC, nhatcher commented on base/src/test/test_column_width.rs
> +    model.workbook.worksheets[0].cols = cols;
You don't need to do this, the default column widths will do.

2024-12-08 01:17 UTC, nhatcher commented on base/src/test/test_column_width.rs
> +    assert!(result.is_err());
Could you do something like:

```rust
assert_eq!(result, Err("some error message".to_string());
```

The reason is hat sometimes we assume it is an error but there is actually a different one

2024-12-08 01:17 UTC, nhatcher commented on webapp/src/components/worksheet.tsx
> +        if (width < 0) return;
Could you use:
```js
if (width < 0) {
  return;
}
```

I will add this rule to biome some day :S

2024-12-08 23:17 UTC, enjoythecode commented
Thanks, addressed the comments.

2024-12-10 17:21 UTC, nhatcher commented
Build is failing because of a formatting issue (just run `cargo fmt`)

2024-12-10 23:06 UTC, nhatcher approved these changes
LGTM!

2024-12-10 23:07 UTC, merged